image:
  repository: dhis2/core
  tag: 2.39.1.1
ingress:
  enabled: true
  hostname: dhis2.dev.test.c.dhis2.org
  path: /
  certIssuer: cert-issuer-prod
catalinaOpts: "-Dcontext.path=/"
startupProbe: # 2min10s (26 * 5 = 130s)
  failureThreshold: 26
  periodSeconds: 5
  path: /
livenessProbe:
  path: /
readinessProbe:
  path: /
dhisConfig: |
  connection.dialect = org.hibernate.dialect.PostgreSQLDialect
  connection.driver_class = org.postgresql.Driver
  connection.url = jdbc:postgresql://dhis2-postgresql.whoami.svc/dhis2
  connection.username = dhis
  connection.password = dhis
  # Database schema behavior, can be validate, update, create, create-drop
  connection.schema = update
  # Server base URL
  server.base.url = https://dhis2-core.127.0.0.1.nip.io/
